# # .github/workflows/ci-postman.yml
# name: CI - Postman API Tests

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   postman-tests:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Reinstall dependencies
#         run: |
#           rm -rf node_modules
#           npm install

#       - name: Install Newman
#         run: npm install -g newman

#       - name: Start Backend Server
#         run: npm start &

#       - name: Wait for server to start
#         run: |
#           for i in {1..10}; do
#             if curl --silent --fail http://localhost:3000; then
#               echo "Server is up!"
#               break
#             fi
#             echo "Waiting for server to start..."
#             sleep 5
#           done

#       - name: Run Postman Collection
#         run: |
#           newman run __tests__/postman/auth-collection.postman_collection.json \
#             --env-var baseUrl=http://localhost:3000/api/auth \
#             --reporters cli,html \
#             --reporter-html-export postman-report.html

#       - name: Upload Postman HTML report
#         if: always()
#         uses: actions/upload-artifact@v4.6.2
#         with:
#           name: postman-report
#           path: postman-report.html
# .github/workflows/ci-postman.yml
name: CI - Postman API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Start Backend Server
        run: npm start &

      - name: Wait for server to be ready
        run: sleep 5

      - name: Run Postman Collection
        run: |
          newman run __tests__/postman/auth-collection.postman_collection.json \
            --env-var baseUrl=http://localhost:3000/api/auth \
            --reporters cli,html \
            --reporter-html-export postman-report.html

      - name: Upload Postman HTML report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: postman-report
          path: postman-report.html
